### ISSUE TITLE
Add a Collection Check View when entering proper store ID

### ISSUE THREAD

**Issue by pedrosolisgarcia** [Pedrosolisg/AS-Catalog#15]
**1. Narrative**

**The purpose of the story is:** As a user administrator making use of the app
After adding proper id in store id pop up, and if there is a new collection available,
I want to display a window that:

- Checks if there is a new collection available,
- Gives the admin the option to update.

So I can choose wether if I want to have the app up to date with the latest collection.

**2. Acceptance Criteria**

- The Collection Check View shall be shown only if the following store ids are submitted: WRO-ID, TEST-ID, and if there is a new collection available.
- The view will check on load if there is a new collection by:
  - retrieving the **_id_** and **_date_** of the collection available on the server
  - If the id does not match with the local, then notify of a new collection available
  - If the id matches the local, check the date
  - If the date does not match, then notify of a new collection available
  - If the date matches, then return

_3. Useful Info_

- https://medium.com/swift-india/userdefaults-under-the-hood-457461c8d262
- https://programmingwithswift.com/save-images-locally-with-swift-5/

**Subtasks**

- [x] Create the view
- [x] Display view if there is version available
- [x] Download the new view and add to UserDefaults
